# my global config
global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    cluster: 'dht22'
    replica: 'r1'

scrape_configs:
# Prometheus self monitoring
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
    - targets:
      - localhost:9090

# MQTT 2 Prometheus application - EU zone - dth22
- job_name: mqtt2prometheus-dth22-eu
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
    - targets:
      - mqtt-2-prometheus-dht22-eu:9641

# MQTT 2 Prometheus application - US zone - dth22
- job_name: mqtt2prometheus-dth22-us
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
    - targets:
      - mqtt-2-prometheus-dht22-us:9641
