version: '3.8'

services:
  # Prometheus + sidecar - dht22 sensors
  prometheus-server-dht22-r1:
    image: prom/prometheus:v2.26.0
    volumes:
      - ./prometheus-server/prometheus-r1.yml:/etc/prometheus/prometheus.yml
      - prometheusserverdht22r1_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.max-block-duration=30m'
      - '--storage.tsdb.min-block-duration=30m'
      - '--web.enable-lifecycle'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    networks:
      - observabilitysandbox
    restart: always
    labels:
      org.label-schema.group: "observability"

  thanos-sidecar-prometheus-dht22-r1:
    image: quay.io/thanos/thanos:v0.18.0
    volumes:
      - ./thanos/:/etc/thanos/
      - prometheusserverdht22r1_data:/prometheus
    command:
      - 'sidecar'
      - '--tsdb.path=/prometheus'
      - '--prometheus.url=http://prometheus-server-dht22-r1:9090'
      - '--grpc-address=0.0.0.0:10091'
      - '--http-address=0.0.0.0:10902'
      - '--objstore.config-file=/etc/thanos/bucket_config.yaml'
    depends_on:
      - prometheus-server-dht22-r1
      - minio-dht22
    networks:
      - observabilitysandbox
    restart: always
    labels:
      org.label-schema.group: "observability"

  prometheus-server-dht22-r2:
    image: prom/prometheus:v2.26.0
    volumes:
      - ./prometheus-server/prometheus-r2.yml:/etc/prometheus/prometheus.yml
      - prometheusserverdht22r2_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.max-block-duration=30m'
      - '--storage.tsdb.min-block-duration=30m'
      - '--web.enable-lifecycle'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9092:9090
    networks:
      - observabilitysandbox
    restart: always
    labels:
      org.label-schema.group: "observability"

  thanos-sidecar-prometheus-dht22-r2:
    image: quay.io/thanos/thanos:v0.18.0
    volumes:
      - ./thanos/:/etc/thanos/
      - prometheusserverdht22r2_data:/prometheus
    command:
      - 'sidecar'
      - '--tsdb.path=/prometheus'
      - '--prometheus.url=http://prometheus-server-dht22-r2:9090'
      - '--grpc-address=0.0.0.0:10091'
      - '--http-address=0.0.0.0:10902'
      - '--objstore.config-file=/etc/thanos/bucket_config.yaml'
    depends_on:
      - prometheus-server-dht22-r2
      - minio-dht22
    networks:
      - observabilitysandbox
    restart: always
    labels:
      org.label-schema.group: "observability"

  # Thanos querier
  thanos-querier-dht22:
    image: quay.io/thanos/thanos:v0.18.0
    command:
      - 'query'
      - '--grpc-address=0.0.0.0:10091'
      - '--http-address=0.0.0.0:10902'
      - '--query.replica-label=replica'
      - '--store=thanos-sidecar-prometheus-dht22-r1:10091'
      - '--store=thanos-sidecar-prometheus-dht22-r2:10091'
      - '--store=thanos-store-gateway-dht22:10091'
    ports:
      - 10903:10902
    depends_on:
      - thanos-sidecar-prometheus-dht22-r1
      - thanos-sidecar-prometheus-dht22-r2
    networks:
      - observabilitysandbox
    restart: always
    labels:
      org.label-schema.group: "observability"

  # Thanos store gateway
  thanos-store-gateway-dht22:
    image: quay.io/thanos/thanos:v0.18.0
    volumes:
      - ./thanos/:/etc/thanos/
    command:
      - 'store'
      - '--grpc-address=0.0.0.0:10091'
      - '--http-address=0.0.0.0:10902'
      - '--data-dir=/tmp/thanos/store'
      - '--objstore.config-file=/etc/thanos/bucket_config.yaml'
    depends_on:
      - minio-dht22
    networks:
      - observabilitysandbox
    restart: always
    labels:
      org.label-schema.group: "observability"

  # Thanos compactor
  thanos-compactor-dht22:
    image: quay.io/thanos/thanos:v0.18.0
    volumes:
      - ./thanos/:/etc/thanos/
    command:
      - 'compact'
      - '--log.level=debug'
      - '--data-dir=/data'
      - '--objstore.config-file=/etc/thanos/bucket_config.yaml'
      - '--wait'
    depends_on:
      - minio-dht22
    networks:
      - observabilitysandbox
    restart: always
    labels:
      org.label-schema.group: "observability"

  # Thanos bucket web
  thanos-bucket-web-dht22:
    image: quay.io/thanos/thanos:v0.18.0
    volumes:
      - ./thanos/:/etc/thanos/
    command:
      - 'tools'
      - 'bucket'
      - 'web'
      - '--http-address=0.0.0.0:10902'
      - '--log.level=debug'
      - '--objstore.config-file=/etc/thanos/bucket_config.yaml'
      - '--refresh=5m'
      - '--timeout=2m'
      - '--label=replica'
    ports:
      - 10912:10902
    depends_on:
      - minio-dht22
    networks:
      - observabilitysandbox
    restart: always
    labels:
      org.label-schema.group: "observability"

  # Minio storage
  minio-dht22:
    image: minio/minio:RELEASE.2020-05-01T22-19-14Z
    volumes:
      - minio_dht22_data:/data
    entrypoint: sh
    command: -c 'mkdir -p /data/dht22-bucket && /usr/bin/minio server /data'
    environment:
      - MINIO_ACCESS_KEY=smth
      - MINIO_SECRET_KEY=Need8Chars
      - MINIO_PROMETHEUS_AUTH_TYPE=public
    ports:
      - 9010:9000
    networks:
      - observabilitysandbox
    restart: always
    labels:
      org.label-schema.group: "observability"

volumes:
  prometheusserverdht22r1_data: {}
  prometheusserverdht22r2_data: {}
  minio_dht22_data: {}

networks:
  observabilitysandbox:
    name: observabilitysandbox
    external: true
